import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from "next/link"

import Slider from '@/components/slider'
import CardProduct from '@/components/card'
import Header from '@/components/header'

import xpander from '../assets/xpander.jpg'
import wa from '../assets/wa.png'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Mitsubshi Promo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <Slider />
        <div>
          <p className="text-5xl font-semibold text-center font-mono pt-5">PROMO</p>

          <div className="p-10">
            <p className="text-xl text-center font-sans">PROMO MITSUBISHI - CIMB NIAGA FINANCE</p>
            
            <div className="flex justify-center p-10">
              <div style={{width: '500px'}}>
                <p className="text-xl font-sans">Pengajuan kredit / pembiayaan di CIMB Niaga Finance :</p>
                <ul className="list-disc pl-8 pt-4">
                  <li>DP 10%* </li>
                  <li>DP 15%* </li>
                  <li>DP 20%* </li>
                </ul>

                <p className="text-xl font-sans pt-10">Dapatkan bonus & hadiah2 menarik :</p>
                <ul className="list-disc pl-8 pt-4">
                  <li>Program Bunga 0% tenor 1 tahun* </li>
                  <li>Tenor sampai 6 tahun </li>
                  <li>Kaca film V-Kool / Ice-U </li>
                  <li>Free jasa servis </li>
                  <li>Free paket smart silver</li>
                  <li>Free tatakan plat</li>
                  <li>Free APAR</li>
                  <li>Free talang air*</li>
                  <li>Free handphone*</li>
                  <li>Dan masih bnyk hadiah lainnya*</li>
                </ul>

                <p className="text-xl font-sans pt-10">Note :</p>
                <p className="text-xl font-sans pt-4">*SYARAT & KETENTUAN BERLAKU</p>
                <p >Yuk di coba pengajuan kredit nya di CIMB Niaga Finance</p>
                <p>Karyawan/wirausaha dengan BI Checking Lancar Bisa Tanpa Survey</p>

                <div className="p-10">
                  <p className="text-xl font-sans text-center">🗣️ *Hallo Sobat Pecinta  Mitsubishi *...🙏😊</p>
                  <p className="text-xl font-sans text-center font-semibold pt-5">M I T S U B I S H I  S U P E R D E A L !</p>
                  <ul className="list-disc pt-4">
                    <li>Kredit Bunga 0% Hingga 1 Tahun* </li>
                    <li>Free Asuransi Hingga 2 Tahun* </li>
                    <li>Kredit DP Ringan* </li>
                    <li>Kredit Angsuran Ringan* </li>
                    <li>Bisa Dibantu Tukar Tambah</li>
                    <li>Nego Sampai Deal</li>
                    <li>Free Accessories Xpander/Pajero*</li>
                    <li>Free Biaya Jasa Service 4 Tahun / 50.000KM</li>
                    <li>Paket Smart Silver (Part, Chemical) 4 Tahun / 50.000KM (Xpander & Pajero Sport)</li>
                    <li>Unit Ready Stock*</li>
                  </ul>
                  <p className="text-xl font-sans text-center pt-5">A V A I L A B L E !!</p>
                  <ul className="list-disc pt-4">
                    <li>PAJERO SPORT </li>
                    <li>XPANDER CROSS </li>
                    <li>ECLIPSE CROSS </li>
                    <li>NEW TRITON </li>
                    <li>L300</li>
                    <li>COLT DIESEL</li>
                    <li>FUSO</li>
                  </ul>

                  <p className="font-sans pt-5">Informasi & Pemesanan :</p>
                  <p className="font-sans"><b>Muhammad Fajar</b> - 088976619319</p>
                </div>

              </div>
            </div>
          </div>
        </div>

        <div className="p-10">
          <p className="text-5xl font-semibold text-center font-mono pt-5">SALES EXECUTIVE</p>
          <p className="text-xl font-sans text-center pt-10">MUHAMMAD FAJAR</p>
          <p className="text-xl font-sans text-center pt-3">HP : 0889 7661 9319 (WA)</p>
        </div>

        <div className="bg-white">
          <p className="text-5xl font-semibold text-center font-mono pt-5">MODEL</p>

          <div className="flex flex-wrap p-10">
            <CardProduct image={xpander} />
            <CardProduct image={xpander} />
            <CardProduct image={xpander} />
            <CardProduct image={xpander} />
            <CardProduct image={xpander} />
            <CardProduct image={xpander} />
            <CardProduct image={xpander} />
            <CardProduct image={xpander} />
          </div>
        </div>

        <div>
          <p className="text-5xl font-semibold text-center font-mono pt-5">LOKASI DEALER</p>

          <div className="flex justify-center p-10">
            <iframe
              width="1000"
              height="450"
              style={{border: 0}}
              loading="lazy"
              allowFullScreen
              referrerPolicy="no-referrer-when-downgrade"
              src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3966.5896498276124!2d106.75214841476891!3d-6.185633395521874!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e69f18b6732f1c5%3A0xee367c946f691c96!2sMITSUBISHI%20DIPO%20PURI%20INDAH%20-%20JAKARTA%20BARAT!5e0!3m2!1sen!2sid!4v1656953118827!5m2!1sen!2sid">
            </iframe>
          </div>
        </div>

        <div className="fixed bottom-10 right-10 rounded-full w-14 h-14">
          <Link href="https://wa.me/088976619319" target="_blank">
            <Image
                  alt="The guitarist in the concert."
                  src={wa}
                  width={60}
                  height={60}
              />
          </Link>
        </div>
      </main>
    </>
  )
}
