import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Header from '@/components/header'
import Table from '@/components/table'

export default function PriceList() {
    const dataTables1 = [
        {
            name: 'New Xpander Ultimate CVT',
            price: '312.100.000',
        },
        {
            name: 'Nex Xpander Sport CVT',
            price: '308.700.000',
        },
        {
            name: 'Nex Xpander Sport M/T',
            price: '294.050.000',
        },
        {
            name: 'Nex Xpander Exceed CVT',
            price: '279.900.000',
        },
        {
            name: 'Nex Xpander Exceed M/T',
            price: '270.700.000',
        },
        {
            name: 'Nex Xpander GLS CVT',
            price: '266.600.000',
        },
        {
            name: 'Nex Xpander GLS M/T',
            price: '257.400.000',
        }
    ]

    const dataTables2 = [
        {
            name: 'Nex Xpander Cross CVT (premium package)',
            price: '338.750.000',
        },
        {
            name: 'Nex Xpander Cross CVT',
            price: '312.950.000',
        },
        {
            name: 'Xpander Cross  CVT  (premium package)',
            price: '329.750.000',
        },
        {
            name: 'Xpander Cross  CVT',
            price: '318.600.000',
        },
        {
            name: 'Xpander Cross  MT',
            price: '303.950.000',
        }
    ]

    return (
        <>
           <Head>
                <title>Pricelist Mitshubishi</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <div className={styles.main}>
                <p className="text-5xl font-semibold text-center font-mono pt-5">PRICELISTS MITSUBISHI</p>

                <div className="p-10">
                    <p className="text-3xl font-semibold text-left font-mono p-5">HARGA MITSUBISHI XPANDER</p>

                    <Table dataTables={dataTables1} />
                </div>

                <div className="p-10">
                    <p className="text-3xl font-semibold text-left font-mono p-5">HARGA MITSUBISHI XPANDER CROSS</p>

                    <Table dataTables={dataTables2} />
                </div>
            </div>
        </>
    )
}